export const TYPES = {
    GET_MOVIES: "GET_MOVIES",

    ORDER_MOVIES: "ORDER_MOVIES",
    FILTER_GENRES: "FILTER_GENRES",
    FILTER_YEARS: "FILTER_YEARS",


    POST_MOVIE: "POST_MOVIE",
    GET_GENRES: "GET_GENRES",
    GET_ACTORS: "GET_ACTORS",    

    GET_TITLE_MOVIE: "GET_TITLE_MOVIE"    


}