export const TYPES = {
    GET_MOVIES: "GET_MOVIES",

    DETAILS: 'DETAILS',
    
    ORDER_MOVIES: "ORDER_MOVIES",
    FILTER_GENRES: "FILTER_GENRES",
    FILTER_YEARS: "FILTER_YEARS",


    POST_MOVIE: "POST_MOVIE",
    GET_GENRES: "GET_GENRES",
    GET_ACTORS: "GET_ACTORS",    

    GET_TITLE_MOVIE: "GET_TITLE_MOVIE",

    CLEAR_MOVIE: "CLEAR_MOVIE",
    MODIFY_MOVIE: "MODIFY_MOVIE",
    DELETE_MOVIE: "DELETE_MOVIE",   

    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADJUST_QTY: "ADJUST_QTY",
    LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
    EMPTY_CART: "EMPTY_CART",

    POST_REVIEW: "POST_REVIEW",
    GET_ALL_REVIEWS: "GET_ALL_REVIEWS",


    GET_USERS: "GET_USERS", 
    DELETE_USER: "DELETE_USER",
    GET_LOGGED_USER: "GET_LOGGED_USER",
    PUT_ROLE: "PUT_ROLE",
    LOGOUT_USER: "LOGOUT_USER",

    
}