export const TYPES = {
    GET_MOVIES: "GET_MOVIES",

    DETAILS: 'DETAILS',
    


    ORDER_MOVIES: "ORDER_MOVIES",
    FILTER_GENRES: "FILTER_GENRES",
    FILTER_YEARS: "FILTER_YEARS",


    POST_MOVIE: "POST_MOVIE",
    GET_GENRES: "GET_GENRES",
    GET_ACTORS: "GET_ACTORS",    

    GET_TITLE_MOVIE: "GET_TITLE_MOVIE",

    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADJUST_QTY: "ADJUST_QTY",
    LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM"

    CLEAR_MOVIE: "CLEAR_MOVIE"    

}